# Generated by Django 5.2.7 on 2025-10-14 16:46

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_widget_document_is_public_contact_documentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='height',
            field=models.FloatField(default=28),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='widget_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='width',
            field=models.FloatField(default=140),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='x_position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='y_position',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DocumentSigningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=core.models.get_default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='core.contact')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_name', models.CharField(max_length=255)),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('field_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_submissions', to='core.document')),
            ],
        ),
    ]
