# Generated by Django 5.2.7 on 2025-10-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_public_token_documentfield_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_modifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='automatic_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='bcc_contacts',
            field=models.ManyToManyField(blank=True, related_name='bcc_documents', to='core.contact'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='core.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_enable_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_tour_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notify_on_signatures',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='remind_once_in_every',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='document',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='request_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='send_in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signers',
            field=models.ManyToManyField(blank=True, related_name='signed_documents', to='core.contact'),
        ),
        migrations.AddField(
            model_name='document',
            name='time_to_complete_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='scenario',
            field=models.CharField(choices=[('self', 'Self Sign'), ('request', 'Request Signatures'), ('template', 'Template')], default='self', max_length=20),
        ),
    ]
