# Generated by Django 5.2.7 on 2025-10-17 19:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'John Doe'", max_length=100)),
                ('type', models.CharField(choices=[('drawn', 'Drawn'), ('typed', 'Typed')], max_length=10)),
                ('image', models.ImageField(help_text='PNG signature image', upload_to=core.models.signature_upload_path)),
                ('font', models.CharField(blank=True, help_text='Font name for typed signatures', max_length=100, null=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color used (e.g., #ff0000)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
