# Generated by Django 5.2.7 on 2025-10-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='is_stamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='signature_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_fields', to='core.widget'),
        ),
    ]
