# Generated by Django 5.2.7 on 2025-10-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_documentfield_is_stamp_documentfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_form_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publicformsubmission',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
